package com.eaio.uuid;

import pdstore.GUID;

/**
* com/eaio/uuid/UUIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from uuid.idl
* Sonntag, 7. März 2004 21.35 Uhr CET
*/


/**
 * The UUID struct.
 */
public final class UUIDHolder implements org.omg.CORBA.portable.Streamable
{
  public GUID value = null;

  public UUIDHolder ()
  {
  }

  public UUIDHolder (GUID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.eaio.uuid.UUIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.eaio.uuid.UUIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.eaio.uuid.UUIDHelper.type ();
  }

}
